### ISSUE TITLE
Week 10 Day 1 - Blog: The series Finally - 

### ISSUE THREAD

**Issue by mdewey** [WebbWear/assignments#37]
We are approaching the final stretch of topics and tonight we will be preparing for the final stretch.

For today, we are going to blogging and practicing everything we have talk about. 

## Objectives
- Practice talking like a developer
- Work on your capstone

## Explorer
- [x] Blog time. Choose a prompt from the following list
    - Using your own experience as inspiration, create a short list of `survival tricks` for a someone entering a boot camp 
    - Pick 1 topic that we have learned and create a blog post explaining it to a new developer
    - Blog about a struggle that you have encountered and overcame during your tenure here so far. 
    - Pick a new technology that we haven't hit yet (or won't) and create a intro blog for that. 

- [ ] Algorithm Practice -- submit a `gist` of your solution for https://www.codewars.com/kata/form-the-minimum in C# or JavaScript

## Adventure
- [ ] Get caught up on any outstanding homework. 
- [ ] Work on your capstone project

**Comment by WebbWear** [comment]
https://medium.com/@webbwear/survival-tricks-for-someone-entering-code-bootcamp-b3f0d2d2c2e2

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media0.giphy.com/media/8hZoGkBJD8nWDZlMeM/200w_d.gif)
